version: "3.8"

services:
  mfe-node:
    build:
      context: ./mfe/docker/node
      target: node
      args:
        DEFAULT_DOCKER_REPO: ${DEFAULT_DOCKER_REPO}
    container_name: mfe-node-builder
    hostname: mfe-node-builder
    volumes:
      - "./mfe:/app"
    working_dir: /app
    command: yarn start:isolated
    environment:
      BASE_URL: "/"
      ARTIFACTORY_URL: ${ARTIFACTORY_URL}
      ARTIFACTORY_USERNAME: ${ARTIFACTORY_USERNAME}
      ARTIFACTORY_ACCESS_TOKEN: ${ARTIFACTORY_ACCESS_TOKEN}
      NPM_REGISTRY: ${NPM_REGISTRY}
    ports:
      - "3006:3006"

  bff:
    build:
      context: ./bff/app
      dockerfile: Dockerfile
      args:
        DOCKER_REPO: ${DEFAULT_DOCKER_REPO}
        ARTIFACTORY_URL: ${ARTIFACTORY_URL}
        ARTIFACTORY_USERNAME: ${ARTIFACTORY_USERNAME}
        ARTIFACTORY_ACCESS_TOKEN: ${ARTIFACTORY_ACCESS_TOKEN}
    container_name: amt-posttrade-bff
    environment:
      ARTIFACTORY_URL: ${ARTIFACTORY_URL}
      ARTIFACTORY_USERNAME: ${ARTIFACTORY_USERNAME}
      ARTIFACTORY_ACCESS_TOKEN: ${ARTIFACTORY_ACCESS_TOKEN}
      ASPNETCORE_URLS: "http://+:8080"
    volumes:
      - "./bff:/workspace:rw"
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    environment:
      BASE_URL: "/"    
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./mfe/dist:/usr/share/nginx/html:ro
    depends_on:
      - bff
